spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USERSERVICE-MICROSERVICES
              predicates:
                - Path=/api/users,/api/users/**
            - id: hotel-service
              uri: lb://HOTELDETAILS
              predicates:
                - Path=/api/hotels,/api/hotels/**
            - id: rating-service
              uri: lb://RATINGSERVICE
              predicates:
                - Path=/api/ratings,/api/ratings/**



server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


